artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://d37ci6vzurychx.cloudfront.net/trip-data/
  local_data: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/yellow_tripdata_2023-03.parquet


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/predSet.csv
  model_path: research/model.bin
  metric_file_name: artifacts/model_evaluation/metrics.json