artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://d37ci6vzurychx.cloudfront.net/trip-data/


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion


model_trainer:
  root_dir: artifacts/model_trainer
  num_trials: 10
  train_data_path: artifacts/data_transformation
  test_data_path: artifacts/data_transformation
  mlflow_uri: "http://127.0.0.1:5000"


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation
  top_n: 5
  ml_uri: "http://127.0.0.1:5000"
  hpo_exp: "random-forest-hyperopt"
  exp_name: "random-forest-best-models"
  rf_params: ['max_depth', 'n_estimators', 'min_samples_split', 'min_samples_leaf', 'random_state']
  